//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmLightMongoVideo1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class theRide
    {
        public string C_id { get; set; }
        public string questionType { get; set; }
        public string questionID { get; set; }
        public string rideID { get; set; }
        public string justTextID { get; set; }
        public string isCorrect { get; set; }
        public string targetDB { get; set; }
        public string answerID { get; set; }
        public string landID { get; set; }
        public string lineValue { get; set; }
    }
}
